language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-baseapp' ]; then cd .. && eval "mv $currentfolder generator-baseapp" && cd generator-baseapp; fi
